/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntornoGraficoYBaseDeDatos;

import javax.swing.JOptionPane;

/**
 *
 * @author cromerofajar
 */
public class Panel extends javax.swing.JFrame {
    public static String usuario;
    String conectado="NO";
    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Bienvenido = new javax.swing.JLabel();
        Pregunta = new javax.swing.JLabel();
        Revisar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        BorrarBuild = new javax.swing.JButton();
        BorrarPartida = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        NombreUsuario = new javax.swing.JTextField();
        NombreUsuarioTexto = new javax.swing.JLabel();
        ConODescon = new javax.swing.JButton();
        CrearBuild = new javax.swing.JButton();
        ConsultarBuild = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPartida = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaBuild = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bienvenido.setText("Desconectado");

        Pregunta.setText("Que accion desea realizar?");

        Revisar.setText("Revisar partidas guardadas");
        Revisar.setEnabled(false);

        Guardar.setText("Guardar una partida");
        Guardar.setEnabled(false);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        BorrarBuild.setText("Borrar una build");
        BorrarBuild.setEnabled(false);

        BorrarPartida.setText("Borrar una partida concreta");
        BorrarPartida.setEnabled(false);

        Modificar.setText("Modificar los datos de una partida");
        Modificar.setEnabled(false);

        Crear.setText("Crear una partida de prueba");
        Crear.setEnabled(false);

        NombreUsuarioTexto.setText("Nombre de usuario");

        ConODescon.setText("Conectar");
        ConODescon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConODesconActionPerformed(evt);
            }
        });

        CrearBuild.setText("Crear una build");
        CrearBuild.setEnabled(false);

        ConsultarBuild.setText("Revisar build");
        ConsultarBuild.setEnabled(false);

        TablaPartida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Partida", "Resultado", "Farmeo", "Kills", "Muertes", "Asistencias", "Vision", "Rango", "Elo"
            }
        ));
        jScrollPane1.setViewportView(TablaPartida);

        TablaBuild.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Build", "1º Objeto", "2º Objeto", "3º Objeto", "4º Objeto", "5º Objeto", "6º Objeto"
            }
        ));
        jScrollPane3.setViewportView(TablaBuild);
        if (TablaBuild.getColumnModel().getColumnCount() > 0) {
            TablaBuild.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Revisar)
                                    .addComponent(ConsultarBuild))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Modificar)
                                    .addComponent(Guardar)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ConODescon))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Bienvenido)
                                        .addComponent(NombreUsuarioTexto)
                                        .addComponent(Pregunta))
                                    .addGap(87, 87, 87))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Crear)
                            .addComponent(CrearBuild))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BorrarBuild)
                            .addComponent(BorrarPartida)))
                    .addComponent(jScrollPane3))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreUsuarioTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConODescon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Bienvenido)
                .addGap(28, 28, 28)
                .addComponent(Pregunta)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Revisar)
                    .addComponent(Crear)
                    .addComponent(Modificar)
                    .addComponent(BorrarPartida))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearBuild)
                    .addComponent(Guardar)
                    .addComponent(ConsultarBuild)
                    .addComponent(BorrarBuild))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConODesconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConODesconActionPerformed
        if(conectado=="NO"&&NombreUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Introduzca un nombre de usuario");
        }else if(conectado=="SI"){
            NombreUsuario.setEditable(true);
            ConODescon.setText("Conectar");
            usuario="";
            Bienvenido.setText("Desconectado");
            Revisar.setEnabled(false);
            ConsultarBuild.setEnabled(false);
            Guardar.setEnabled(false);
            BorrarBuild.setEnabled(false);
            BorrarPartida.setEnabled(false);
            Modificar.setEnabled(false);
            Crear.setEnabled(false);
            CrearBuild.setEnabled(false);
            conectado="NO";
        }else if(conectado=="NO"){
            NombreUsuario.setEditable(false);
            ConODescon.setText("Desconectar");
            usuario=NombreUsuario.getText();
            Bienvenido.setText("Bienvenido "+usuario);
            Revisar.setEnabled(true);
            ConsultarBuild.setEnabled(true);
            Guardar.setEnabled(true);
            BorrarBuild.setEnabled(true);
            BorrarPartida.setEnabled(true);
            Modificar.setEnabled(true);
            Crear.setEnabled(true);
            CrearBuild.setEnabled(true);
            NombreUsuario.setText("");
            conectado="SI";
        }
    }//GEN-LAST:event_ConODesconActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        CrearGuardar obx=new CrearGuardar();
        obx.setVisible(true);
        
        
        
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JButton BorrarBuild;
    private javax.swing.JButton BorrarPartida;
    private javax.swing.JButton ConODescon;
    private javax.swing.JButton ConsultarBuild;
    private javax.swing.JButton Crear;
    private javax.swing.JButton CrearBuild;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JLabel NombreUsuarioTexto;
    private javax.swing.JLabel Pregunta;
    private javax.swing.JButton Revisar;
    private javax.swing.JTable TablaBuild;
    private javax.swing.JTable TablaPartida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
